version: '3.8'

services:
  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: email-worker-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management console
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Email worker service
  email-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-worker
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - API_BASE_URL=${API_BASE_URL}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - WORKER_CONCURRENCY=5
      - LOG_LEVEL=info
      - ENABLE_HEALTH_CHECK=true
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

volumes:
  rabbitmq_data: